[[libharu]]
arch = "aarch64"
git-tree-sha1 = "b696b7cea7f72e1bd91c9ee8a6eb95f452111366"
os = "macos"

    [[libharu.download]]
    sha256 = "8496e6982b936cc9f396f39dc729c4f79b43a3aa253f76ba9bc4a83eab1c3ec6"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.aarch64-apple-darwin.tar.gz"
[[libharu]]
arch = "aarch64"
git-tree-sha1 = "41c755e8fc2bebc21b1aea515b044daf5bc8439f"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "12fb049b1c2086092bf4da8951d0df63f0493cd60a538ce031f7cec70ce08729"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.aarch64-linux-gnu.tar.gz"
[[libharu]]
arch = "aarch64"
git-tree-sha1 = "0dfc3b42ab6412b7a7f741ca83a9568c5020b689"
libc = "musl"
os = "linux"

    [[libharu.download]]
    sha256 = "33a089816509b830e327962b0225b3ee40979444da435c76f0a2b0b83a7664f7"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.aarch64-linux-musl.tar.gz"
[[libharu]]
arch = "aarch64"
git-tree-sha1 = "7166d3f4df6c70abae5646df5ad0d226edda0e8a"
os = "freebsd"

    [[libharu.download]]
    sha256 = "13bcfe2a56b247aa681645aa6781f42dbf9be47e1d8974d2a297ee73ca4e0680"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.aarch64-unknown-freebsd.tar.gz"
[[libharu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "25faf90f995b6bfb90fd29b41f1cefe98ce75402"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "c4c508a4483ec7bd05b3cc30f978e999820d5e0b4bc3d740b06cfe4c4404252f"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.armv6l-linux-gnueabihf.tar.gz"
[[libharu]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93c71a0fbf35467a2d24893e6ef38c02698979f1"
libc = "musl"
os = "linux"

    [[libharu.download]]
    sha256 = "b2db6032f18e0fb592f1a7f7c643bab1e7da9459f776e87e07e88aa05999a4a2"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.armv6l-linux-musleabihf.tar.gz"
[[libharu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f69f10870630a90fa86401893b7367cfc9ff6f08"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "223bab6c4416dc893f019f9840ad0fb9a361ac3fac55b55be9f8044e60a44d64"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.armv7l-linux-gnueabihf.tar.gz"
[[libharu]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0bb559b1f4b0347e5ed9aaf453b1b48504fd4f2b"
libc = "musl"
os = "linux"

    [[libharu.download]]
    sha256 = "c5833643f9e29d2bf6214883a29d2ceee55e7af126f624b4d5270040ae8a2d48"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.armv7l-linux-musleabihf.tar.gz"
[[libharu]]
arch = "i686"
git-tree-sha1 = "eea5da3eddd153a335682b01c9d2e3b8e027905c"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "38401067b0be20b99a389ace15da9e796fb34dbb57382661e66c9513a1a45bf2"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.i686-linux-gnu.tar.gz"
[[libharu]]
arch = "i686"
git-tree-sha1 = "9ec304a1f8732b2b44d8a4464a582ddbc8e90d99"
libc = "musl"
os = "linux"

    [[libharu.download]]
    sha256 = "f415caab32674830b04368b35bedca1d0c8952527af193a21b41cd8b412e4f09"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.i686-linux-musl.tar.gz"
[[libharu]]
arch = "i686"
git-tree-sha1 = "1e28a7a1d5d8d7c9e7824287d2252179e21c7a0d"
os = "windows"

    [[libharu.download]]
    sha256 = "d8dffc6957e610247501795f35cdd56e5ad647d423409d9726c6eb5b66aef04e"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.i686-w64-mingw32.tar.gz"
[[libharu]]
arch = "powerpc64le"
git-tree-sha1 = "275068ac412f2a8b7f7219fce0cfed92fdd626d9"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "c61f0ed1fb1ef19722f10aff029bbb167576460a7f79761b640f0011a21dd042"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.powerpc64le-linux-gnu.tar.gz"
[[libharu]]
arch = "riscv64"
git-tree-sha1 = "55839c440e5d55c48a2874f17e8b5bba611a11df"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "de24e3af35f742e3195ae40648dffc7fd28d94e77de39052b5c59bbbc201ba2b"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.riscv64-linux-gnu.tar.gz"
[[libharu]]
arch = "x86_64"
git-tree-sha1 = "c619e4b9071367d43ab8b7d9ff4b8cb521cfb7d5"
os = "macos"

    [[libharu.download]]
    sha256 = "74e078d2e3e57864c8060c35009ba25325c1b14cb2b5dca2bbfb04cdaddd95b2"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.x86_64-apple-darwin.tar.gz"
[[libharu]]
arch = "x86_64"
git-tree-sha1 = "524e8dd6079ff5f6a0b29d9939caf91194faa55f"
libc = "glibc"
os = "linux"

    [[libharu.download]]
    sha256 = "a9f8a7b6b4029d084cd9ea26514c46ac7d546608e4d153277903c6f979d2f17e"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.x86_64-linux-gnu.tar.gz"
[[libharu]]
arch = "x86_64"
git-tree-sha1 = "015402fc787461970be48d1e436bd95ff4be640f"
libc = "musl"
os = "linux"

    [[libharu.download]]
    sha256 = "1c7566ec7ee8d757438f02b89422d102daaf8468bb96cf42ac20e5a2c179a0b4"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.x86_64-linux-musl.tar.gz"
[[libharu]]
arch = "x86_64"
git-tree-sha1 = "f1284454bb5af4f2a16df9fb3e3b2c112e67d2a4"
os = "freebsd"

    [[libharu.download]]
    sha256 = "1a3618684354121543e3278e248105c6ad86ccb8692339e097f13bc678669032"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.x86_64-unknown-freebsd.tar.gz"
[[libharu]]
arch = "x86_64"
git-tree-sha1 = "4e30a230cd6f42fd332043848e2184996ee09151"
os = "windows"

    [[libharu.download]]
    sha256 = "682fe13534249f94384d84888609c652d0f001febd3dcebd946647e3098d302c"
    url = "https://github.com/JuliaBinaryWrappers/libharu_jll.jl/releases/download/libharu-v2.4.5+0/libharu.v2.4.5.x86_64-w64-mingw32.tar.gz"
