# Autogenerated wrapper script for libharu_jll for i686-w64-mingw32
export libhpdf

using Zlib_jll
using libpng_jll
JLLWrappers.@generate_wrapper_header("libharu")
JLLWrappers.@declare_library_product(libhpdf, "libhpdf.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libpng_jll)
    JLLWrappers.@init_library_product(
        libhpdf,
        "bin\\libhpdf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
